set_property IOSTANDARD LVCMOS33 [get_ports key]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property PACKAGE_PIN K16 [get_ports key]
set_property PACKAGE_PIN U18 [get_ports sys_clk]
set_property PACKAGE_PIN H16 [get_ports {led[2]}]
set_property PACKAGE_PIN H17 [get_ports {led[1]}]
set_property PACKAGE_PIN J16 [get_ports {led[0]}]

set_property PACKAGE_PIN R17 [get_ports sys_rst]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst]